# Generated by Django 3.2.3 on 2021-06-10 04:36

import django.db.models.deletion
import django_fsm
from django.db import migrations, models

import common.pagination


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('state', django_fsm.FSMField(default='new', max_length=50, protected=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
            bases=(models.Model, common.pagination.PaginationSearchable, common.pagination.PaginationSortable,
                   common.pagination.PaginationFilterable),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='BookLoanHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_request_date', models.DateField(auto_now_add=True, null=True)),
                ('back_date', models.DateField(blank=True, editable=False, null=True)),
                ('state', django_fsm.FSMField(default='new', max_length=50, protected=True)),
                ('book', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT,
                                           related_name='loan_histories', to='book.book')),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT,
                                               related_name='loan_histories', to='users.customer')),
            ],
            options={
                'verbose_name_plural': 'Book Rent Histories',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='prerequisite',
            field=models.ManyToManyField(related_name='_book_book_prerequisite_+', to='book.Book'),
        ),
    ]
